### ISSUE TITLE
valid url reported as an error.

### ISSUE THREAD

**Issue by tacman** [Pierstoval/SmokeTesting#14]
First, the app, which uses SQLite for easy testing.

```bash
git clone git@github.com:survos-sites/barcode-demo.git && cd barcode-demo
composer install
bin/console doctrine:schema:update --force
bin/console app:load-products
symfony server:start -d
symfony open:local 
```

Now test.  It uses the same database for dev and test, but for completeness you can reload

```bash
vendor/bin/phpunit --testdox-text=testdox.txt
cat testdox.txt
symfony open:local --path="/info"
```

/info is valid (it returns json and a 200 response).

For clickable links, tweak the default uri in framework.yaml or set the proxy to barcode

```
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        router:
            # change to the IP if not using symfony proxy (symfony proxy:domain:attach barcode)
            default_uri: 'https://barcode.wip/'
```
